Guard scrollTo call so that Jest completes
When testing with Jest in my project I get `TypeError: _this._scrollView.scrollTo is not a function`. Add this simple condition makes all my tests pass. If there's a better way to fix this that would be appreciated!